name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      package-name:
        description: "Package to publish"
        required: true
        type: choice
        options:
          - inspect_ai
          - inspect_tool_support
        default: "inspect_ai"
      publish-release:
        description: "Production Release"
        required: false
        type: boolean
        default: false

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: pypi
    strategy:
      fail-fast: false
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Set working directory for inspect_tool_support
        if: ${{ inputs.package-name == 'inspect_tool_support' }}
        run: cd src/inspect_tool_support
      - name: Build
        run: python -m build
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ ! inputs.publish-release }}
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: ${{ inputs.package-name == 'inspect_tool_support' && 'src/inspect_tool_support/dist/' || 'dist/' }}
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ inputs.publish-release }}
        with:
          packages-dir: ${{ inputs.package-name == 'inspect_tool_support' && 'src/inspect_tool_support/dist/' || 'dist/' }}
